
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.StringTokenizer;

/*
ID: samgear2
LANG: JAVA
PROG: friday
 */
public class friday {
static ArrayList<String> sam;
static ArrayList<String> john;
static ArrayList<String> josh;
static ArrayList<Integer> numbers;    
    public static void main(String[] args) throws IOException{
 File in = new File("friday.in");
File out = new File("friday.out");
int baseYear=1900;
int base = 1900;
in.createNewFile();
out.createNewFile();

int start;
int n=1;
int index=0;
int what=0;
int stop;

sam = new ArrayList<String>();
john = new ArrayList<String>();
josh=new ArrayList<String>();
numbers=new ArrayList<Integer>();

sam.add("January");
sam.add("31");
sam.add("February");
sam.add("28");
sam.add("March");
sam.add("31");
sam.add("April");
sam.add("30");
sam.add("May");
sam.add("31");
sam.add("June");
sam.add("30");
sam.add("July");
sam.add("31");
sam.add("August");
sam.add("31");
sam.add("September");
sam.add("30");
sam.add("October");
sam.add("31");
sam.add("November");
sam.add("30");
sam.add("December");
sam.add("31");

john.add("Sunday");//0
john.add("Monday");//1
john.add("Tuesday");//2
john.add("Wednesday");//3
john.add("Thursday");//4
john.add("Friday");//5
john.add("Saturday");//6
john.add("Sunday");//7
john.add("Monday");//8
john.add("Tuesday");//9
john.add("Wednesday");//10
john.add("Thursday");//11
john.add("Friday");//12
john.add("Saturday");//13
john.add("Sunday");//14
john.add("Monday");//15
john.add("Tuesday");//16
john.add("Wednesday");//17
john.add("Thursday");//18
john.add("Friday");//19
john.add("Saturday");//20
john.add("Sunday");//21
john.add("Monday");//22
john.add("Tuesday");//23
john.add("Wednesday");//24
john.add("Thursday");//25
john.add("Friday");//26
john.add("Saturday");//27
john.add("Sunday");//28
john.add("Monday");//29
john.add("Tuesday");//30
john.add("Wednesday");//31
john.add("Thursday");//32
john.add("Friday");//33
john.add("Saturday");//34
john.add("Sunday");//35
john.add("Monday");//36
john.add("Tuesday");//37
john.add("Wednesday");//38
john.add("Thursday");//39
john.add("Friday");//40
john.add("Saturday");//41
john.add("Sunday");//42
john.add("Monday");//43
john.add("Tuesday");//44
john.add("Wednesday");//45
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//49
john.add("Monday");//50
john.add("Tuesday");//51
john.add("Wednesday");//52
john.add("Thursday");//53
john.add("Friday");//54
john.add("Saturday");//55
john.add("Sunday");//56
john.add("Monday");//57
john.add("Tuesday");//58
john.add("Wednesday");//59
john.add("Thursday");//60
john.add("Friday");//61
john.add("Saturday");//62
john.add("Sunday");//63
john.add("Monday");//64
john.add("Tuesday");//65
john.add("Wednesday");//66
john.add("Thursday");//67
john.add("Friday");//68
john.add("Saturday");//69
john.add("Sunday");//70
john.add("Monday");//71
john.add("Tuesday");//72
john.add("Wednesday");//73
john.add("Thursday");//74
john.add("Friday");//75
john.add("Saturday");//76
john.add("Sunday");//77
john.add("Monday");//78
john.add("Tuesday");//79
john.add("Wednesday");//80
john.add("Thursday");//81
john.add("Friday");//82
john.add("Saturday");//83
john.add("Sunday");//84
john.add("Monday");//85
john.add("Tuesday");//86
john.add("Wednesday");//87
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//0
john.add("Monday");//1
john.add("Tuesday");//2
john.add("Wednesday");//3
john.add("Thursday");//4
john.add("Friday");//5
john.add("Saturday");//6
john.add("Sunday");//7
john.add("Monday");//8
john.add("Tuesday");//9
john.add("Wednesday");//10
john.add("Thursday");//11
john.add("Friday");//12
john.add("Saturday");//13
john.add("Sunday");//14
john.add("Monday");//15
john.add("Tuesday");//16
john.add("Wednesday");//17
john.add("Thursday");//18
john.add("Friday");//19
john.add("Saturday");//20
john.add("Sunday");//21
john.add("Monday");//22
john.add("Tuesday");//23
john.add("Wednesday");//24
john.add("Thursday");//25
john.add("Friday");//26
john.add("Saturday");//27
john.add("Sunday");//28
john.add("Monday");//29
john.add("Tuesday");//30
john.add("Wednesday");//31
john.add("Thursday");//32
john.add("Friday");//33
john.add("Saturday");//34
john.add("Sunday");//35
john.add("Monday");//36
john.add("Tuesday");//37
john.add("Wednesday");//38
john.add("Thursday");//39
john.add("Friday");//40
john.add("Saturday");//41
john.add("Sunday");//42
john.add("Monday");//43
john.add("Tuesday");//44
john.add("Wednesday");//45
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//49
john.add("Monday");//50
john.add("Tuesday");//51
john.add("Wednesday");//52
john.add("Thursday");//53
john.add("Friday");//54
john.add("Saturday");//55
john.add("Sunday");//56
john.add("Monday");//57
john.add("Tuesday");//58
john.add("Wednesday");//59
john.add("Thursday");//60
john.add("Friday");//61
john.add("Saturday");//62
john.add("Sunday");//63
john.add("Monday");//64
john.add("Tuesday");//65
john.add("Wednesday");//66
john.add("Thursday");//67
john.add("Friday");//68
john.add("Saturday");//69
john.add("Sunday");//70
john.add("Monday");//71
john.add("Tuesday");//72
john.add("Wednesday");//73
john.add("Thursday");//74
john.add("Friday");//75
john.add("Saturday");//76
john.add("Sunday");//77
john.add("Monday");//78
john.add("Tuesday");//79
john.add("Wednesday");//80
john.add("Thursday");//81
john.add("Friday");//82
john.add("Saturday");//83
john.add("Sunday");//84
john.add("Monday");//85
john.add("Tuesday");//86
john.add("Wednesday");//87
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//0
john.add("Monday");//1
john.add("Tuesday");//2
john.add("Wednesday");//3
john.add("Thursday");//4
john.add("Friday");//5
john.add("Saturday");//6
john.add("Sunday");//7
john.add("Monday");//8
john.add("Tuesday");//9
john.add("Wednesday");//10
john.add("Thursday");//11
john.add("Friday");//12
john.add("Saturday");//13
john.add("Sunday");//14
john.add("Monday");//15
john.add("Tuesday");//16
john.add("Wednesday");//17
john.add("Thursday");//18
john.add("Friday");//19
john.add("Saturday");//20
john.add("Sunday");//21
john.add("Monday");//22
john.add("Tuesday");//23
john.add("Wednesday");//24
john.add("Thursday");//25
john.add("Friday");//26
john.add("Saturday");//27
john.add("Sunday");//28
john.add("Monday");//29
john.add("Tuesday");//30
john.add("Wednesday");//31
john.add("Thursday");//32
john.add("Friday");//33
john.add("Saturday");//34
john.add("Sunday");//35
john.add("Monday");//36
john.add("Tuesday");//37
john.add("Wednesday");//38
john.add("Thursday");//39
john.add("Friday");//40
john.add("Saturday");//41
john.add("Sunday");//42
john.add("Monday");//43
john.add("Tuesday");//44
john.add("Wednesday");//45
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//49
john.add("Monday");//50
john.add("Tuesday");//51
john.add("Wednesday");//52
john.add("Thursday");//53
john.add("Friday");//54
john.add("Saturday");//55
john.add("Sunday");//56
john.add("Monday");//57
john.add("Tuesday");//58
john.add("Wednesday");//59
john.add("Thursday");//60
john.add("Friday");//61
john.add("Saturday");//62
john.add("Sunday");//63
john.add("Monday");//64
john.add("Tuesday");//65
john.add("Wednesday");//66
john.add("Thursday");//67
john.add("Friday");//68
john.add("Saturday");//69
john.add("Sunday");//70
john.add("Monday");//71
john.add("Tuesday");//72
john.add("Wednesday");//73
john.add("Thursday");//74
john.add("Friday");//75
john.add("Saturday");//76
john.add("Sunday");//77
john.add("Monday");//78
john.add("Tuesday");//79
john.add("Wednesday");//80
john.add("Thursday");//81
john.add("Friday");//82
john.add("Saturday");//83
john.add("Sunday");//84
john.add("Monday");//85
john.add("Tuesday");//86
john.add("Wednesday");//87
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//0
john.add("Monday");//1
john.add("Tuesday");//2
john.add("Wednesday");//3
john.add("Thursday");//4
john.add("Friday");//5
john.add("Saturday");//6
john.add("Sunday");//7
john.add("Monday");//8
john.add("Tuesday");//9
john.add("Wednesday");//10
john.add("Thursday");//11
john.add("Friday");//12
john.add("Saturday");//13
john.add("Sunday");//14
john.add("Monday");//15
john.add("Tuesday");//16
john.add("Wednesday");//17
john.add("Thursday");//18
john.add("Friday");//19
john.add("Saturday");//20
john.add("Sunday");//21
john.add("Monday");//22
john.add("Tuesday");//23
john.add("Wednesday");//24
john.add("Thursday");//25
john.add("Friday");//26
john.add("Saturday");//27
john.add("Sunday");//28
john.add("Monday");//29
john.add("Tuesday");//30
john.add("Wednesday");//31
john.add("Thursday");//32
john.add("Friday");//33
john.add("Saturday");//34
john.add("Sunday");//35
john.add("Monday");//36
john.add("Tuesday");//37
john.add("Wednesday");//38
john.add("Thursday");//39
john.add("Friday");//40
john.add("Saturday");//41
john.add("Sunday");//42
john.add("Monday");//43
john.add("Tuesday");//44
john.add("Wednesday");//45
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//49
john.add("Monday");//50
john.add("Tuesday");//51
john.add("Wednesday");//52
john.add("Thursday");//53
john.add("Friday");//54
john.add("Saturday");//55
john.add("Sunday");//56
john.add("Monday");//57
john.add("Tuesday");//58
john.add("Wednesday");//59
john.add("Thursday");//60
john.add("Friday");//61
john.add("Saturday");//62
john.add("Sunday");//63
john.add("Monday");//64
john.add("Tuesday");//65
john.add("Wednesday");//66
john.add("Thursday");//67
john.add("Friday");//68
john.add("Saturday");//69
john.add("Sunday");//70
john.add("Monday");//71
john.add("Tuesday");//72
john.add("Wednesday");//73
john.add("Thursday");//74
john.add("Friday");//75
john.add("Saturday");//76
john.add("Sunday");//77
john.add("Monday");//78
john.add("Tuesday");//79
john.add("Wednesday");//80
john.add("Thursday");//81
john.add("Friday");//82
john.add("Saturday");//83
john.add("Sunday");//84
john.add("Monday");//85
john.add("Tuesday");//86
john.add("Wednesday");//87
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//0
john.add("Monday");//1
john.add("Tuesday");//2
john.add("Wednesday");//3
john.add("Thursday");//4
john.add("Friday");//5
john.add("Saturday");//6
john.add("Sunday");//7
john.add("Monday");//8
john.add("Tuesday");//9
john.add("Wednesday");//10
john.add("Thursday");//11
john.add("Friday");//12
john.add("Saturday");//13
john.add("Sunday");//14
john.add("Monday");//15
john.add("Tuesday");//16
john.add("Wednesday");//17
john.add("Thursday");//18
john.add("Friday");//19
john.add("Saturday");//20
john.add("Sunday");//21
john.add("Monday");//22
john.add("Tuesday");//23
john.add("Wednesday");//24
john.add("Thursday");//25
john.add("Friday");//26
john.add("Saturday");//27
john.add("Sunday");//28
john.add("Monday");//29
john.add("Tuesday");//30
john.add("Wednesday");//31
john.add("Thursday");//32
john.add("Friday");//33
john.add("Saturday");//34
john.add("Sunday");//35
john.add("Monday");//36
john.add("Tuesday");//37
john.add("Wednesday");//38
john.add("Thursday");//39
john.add("Friday");//40
john.add("Saturday");//41
john.add("Sunday");//42
john.add("Monday");//43
john.add("Tuesday");//44
john.add("Wednesday");//45
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//49
john.add("Monday");//50
john.add("Tuesday");//51
john.add("Wednesday");//52
john.add("Thursday");//53
john.add("Friday");//54
john.add("Saturday");//55
john.add("Sunday");//56
john.add("Monday");//57
john.add("Tuesday");//58
john.add("Wednesday");//59
john.add("Thursday");//60
john.add("Friday");//61
john.add("Saturday");//62
john.add("Sunday");//63
john.add("Monday");//64
john.add("Tuesday");//65
john.add("Wednesday");//66
john.add("Thursday");//67
john.add("Friday");//68
john.add("Saturday");//69
john.add("Sunday");//70
john.add("Monday");//71
john.add("Tuesday");//72
john.add("Wednesday");//73
john.add("Thursday");//74
john.add("Friday");//75
john.add("Saturday");//76
john.add("Sunday");//77
john.add("Monday");//78
john.add("Tuesday");//79
john.add("Wednesday");//80
john.add("Thursday");//81
john.add("Friday");//82
john.add("Saturday");//83
john.add("Sunday");//84
john.add("Monday");//85
john.add("Tuesday");//86
john.add("Wednesday");//87
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//0
john.add("Monday");//1
john.add("Tuesday");//2
john.add("Wednesday");//3
john.add("Thursday");//4
john.add("Friday");//5
john.add("Saturday");//6
john.add("Sunday");//7
john.add("Monday");//8
john.add("Tuesday");//9
john.add("Wednesday");//10
john.add("Thursday");//11
john.add("Friday");//12
john.add("Saturday");//13
john.add("Sunday");//14
john.add("Monday");//15
john.add("Tuesday");//16
john.add("Wednesday");//17
john.add("Thursday");//18
john.add("Friday");//19
john.add("Saturday");//20
john.add("Sunday");//21
john.add("Monday");//22
john.add("Tuesday");//23
john.add("Wednesday");//24
john.add("Thursday");//25
john.add("Friday");//26
john.add("Saturday");//27
john.add("Sunday");//28
john.add("Monday");//29
john.add("Tuesday");//30
john.add("Wednesday");//31
john.add("Thursday");//32
john.add("Friday");//33
john.add("Saturday");//34
john.add("Sunday");//35
john.add("Monday");//36
john.add("Tuesday");//37
john.add("Wednesday");//38
john.add("Thursday");//39
john.add("Friday");//40
john.add("Saturday");//41
john.add("Sunday");//42
john.add("Monday");//43
john.add("Tuesday");//44
john.add("Wednesday");//45
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//49
john.add("Monday");//50
john.add("Tuesday");//51
john.add("Wednesday");//52
john.add("Thursday");//53
john.add("Friday");//54
john.add("Saturday");//55
john.add("Sunday");//56
john.add("Monday");//57
john.add("Tuesday");//58
john.add("Wednesday");//59
john.add("Thursday");//60
john.add("Friday");//61
john.add("Saturday");//62
john.add("Sunday");//63
john.add("Monday");//64
john.add("Tuesday");//65
john.add("Wednesday");//66
john.add("Thursday");//67
john.add("Friday");//68
john.add("Saturday");//69
john.add("Sunday");//70
john.add("Monday");//71
john.add("Tuesday");//72
john.add("Wednesday");//73
john.add("Thursday");//74
john.add("Friday");//75
john.add("Saturday");//76
john.add("Sunday");//77
john.add("Monday");//78
john.add("Tuesday");//79
john.add("Wednesday");//80
john.add("Thursday");//81
john.add("Friday");//82
john.add("Saturday");//83
john.add("Sunday");//84
john.add("Monday");//85
john.add("Tuesday");//86
john.add("Wednesday");//87
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//0
john.add("Monday");//1
john.add("Tuesday");//2
john.add("Wednesday");//3
john.add("Thursday");//4
john.add("Friday");//5
john.add("Saturday");//6
john.add("Sunday");//7
john.add("Monday");//8
john.add("Tuesday");//9
john.add("Wednesday");//10
john.add("Thursday");//11
john.add("Friday");//12
john.add("Saturday");//13
john.add("Sunday");//14
john.add("Monday");//15
john.add("Tuesday");//16
john.add("Wednesday");//17
john.add("Thursday");//18
john.add("Friday");//19
john.add("Saturday");//20
john.add("Sunday");//21
john.add("Monday");//22
john.add("Tuesday");//23
john.add("Wednesday");//24
john.add("Thursday");//25
john.add("Friday");//26
john.add("Saturday");//27
john.add("Sunday");//28
john.add("Monday");//29
john.add("Tuesday");//30
john.add("Wednesday");//31
john.add("Thursday");//32
john.add("Friday");//33
john.add("Saturday");//34
john.add("Sunday");//35
john.add("Monday");//36
john.add("Tuesday");//37
john.add("Wednesday");//38
john.add("Thursday");//39
john.add("Friday");//40
john.add("Saturday");//41
john.add("Sunday");//42
john.add("Monday");//43
john.add("Tuesday");//44
john.add("Wednesday");//45
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//49
john.add("Monday");//50
john.add("Tuesday");//51
john.add("Wednesday");//52
john.add("Thursday");//53
john.add("Friday");//54
john.add("Saturday");//55
john.add("Sunday");//56
john.add("Monday");//57
john.add("Tuesday");//58
john.add("Wednesday");//59
john.add("Thursday");//60
john.add("Friday");//61
john.add("Saturday");//62
john.add("Sunday");//63
john.add("Monday");//64
john.add("Tuesday");//65
john.add("Wednesday");//66
john.add("Thursday");//67
john.add("Friday");//68
john.add("Saturday");//69
john.add("Sunday");//70
john.add("Monday");//71
john.add("Tuesday");//72
john.add("Wednesday");//73
john.add("Thursday");//74
john.add("Friday");//75
john.add("Saturday");//76
john.add("Sunday");//77
john.add("Monday");//78
john.add("Tuesday");//79
john.add("Wednesday");//80
john.add("Thursday");//81
john.add("Friday");//82
john.add("Saturday");//83
john.add("Sunday");//84
john.add("Monday");//85
john.add("Tuesday");//86
john.add("Wednesday");//87
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//0
john.add("Monday");//1
john.add("Tuesday");//2
john.add("Wednesday");//3
john.add("Thursday");//4
john.add("Friday");//5
john.add("Saturday");//6
john.add("Sunday");//7
john.add("Monday");//8
john.add("Tuesday");//9
john.add("Wednesday");//10
john.add("Thursday");//11
john.add("Friday");//12
john.add("Saturday");//13
john.add("Sunday");//14
john.add("Monday");//15
john.add("Tuesday");//16
john.add("Wednesday");//17
john.add("Thursday");//18
john.add("Friday");//19
john.add("Saturday");//20
john.add("Sunday");//21
john.add("Monday");//22
john.add("Tuesday");//23
john.add("Wednesday");//24
john.add("Thursday");//25
john.add("Friday");//26
john.add("Saturday");//27
john.add("Sunday");//28
john.add("Monday");//29
john.add("Tuesday");//30
john.add("Wednesday");//31
john.add("Thursday");//32
john.add("Friday");//33
john.add("Saturday");//34
john.add("Sunday");//35
john.add("Monday");//36
john.add("Tuesday");//37
john.add("Wednesday");//38
john.add("Thursday");//39
john.add("Friday");//40
john.add("Saturday");//41
john.add("Sunday");//42
john.add("Monday");//43
john.add("Tuesday");//44
john.add("Wednesday");//45
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48
john.add("Sunday");//49
john.add("Monday");//50
john.add("Tuesday");//51
john.add("Wednesday");//52
john.add("Thursday");//53
john.add("Friday");//54
john.add("Saturday");//55
john.add("Sunday");//56
john.add("Monday");//57
john.add("Tuesday");//58
john.add("Wednesday");//59
john.add("Thursday");//60
john.add("Friday");//61
john.add("Saturday");//62
john.add("Sunday");//63
john.add("Monday");//64
john.add("Tuesday");//65
john.add("Wednesday");//66
john.add("Thursday");//67
john.add("Friday");//68
john.add("Saturday");//69
john.add("Sunday");//70
john.add("Monday");//71
john.add("Tuesday");//72
john.add("Wednesday");//73
john.add("Thursday");//74
john.add("Friday");//75
john.add("Saturday");//76
john.add("Sunday");//77
john.add("Monday");//78
john.add("Tuesday");//79
john.add("Wednesday");//80
john.add("Thursday");//81
john.add("Friday");//82
john.add("Saturday");//83
john.add("Sunday");//84
john.add("Monday");//85
john.add("Tuesday");//86
john.add("Wednesday");//87
john.add("Thursday");//46
john.add("Friday");//47
john.add("Saturday");//48


josh.add("Sunday");//0
josh.add("Monday");//1
josh.add("Tuesday");//2
josh.add("Wednesday");//3
josh.add("Thursday");//4
josh.add("Friday");//5
josh.add("Saturday");//6

numbers.add(0);
numbers.add(0);
numbers.add(0);
numbers.add(0);
numbers.add(0);
numbers.add(0);
numbers.add(0);

BufferedReader br = new BufferedReader(new FileReader(in));
PrintWriter pw = new PrintWriter(new BufferedWriter(new FileWriter(out)));
StringTokenizer st = new StringTokenizer(br.readLine());
int year = Integer.parseInt(st.nextToken());
outer: for(start=1;start<=700;start++){ 
    if((base % 4==0 && base % 100!=0) 
            || (base % 4 ==0 && base % 100==0 && base % 400 ==0)){
        sam.set(3, "29");
    }
    else{
        sam.set(3, "28");
    }
        stop = what;
    for(int i=0;i<josh.size();i++){
   if(start==13 + what && john.get(13 + what).equals(josh.get(i))){
     numbers.set(i, numbers.get(i) + 1);
   } 
}
    if(start==13 + what){    
what = josh.indexOf(john.get(Integer.parseInt(sam.get(n)) + 1)) + what-1;
}
if(n==23 && start==13 + stop && base % 4==0 && base % 100!=0){
    baseYear+=2;
}
else if(n==23 && start==13 + stop && base % 4==0 && base % 100==0 && base % 400 !=0){
    baseYear++;
}
else if(n==23 && start==13 + stop && base % 4 !=0){
    baseYear++;
}
else if(n==23 && start==13 + stop && base % 4 ==0 && base % 100==0 && base % 400 ==0){
    baseYear+=2;
}
if(n==23 && start==13 + stop && index<year*12-1){
 base++;
 n=1;
 index++;
 start=0;  
 what=baseYear-1900;
 continue outer; 
}
if(start==13 + stop && n !=23 && index<year*12-1){
n+=2;
index++;
start=0;
continue outer;
}
if(start==13 + stop){
if(index>year * 12 -2){
    break;
}
}
}
pw.print(numbers.get(6));
for(int i=0;i<6;i++){
    pw.print(" " + numbers.get(i));
}
pw.print("\n");
pw.close();
System.exit(0);       
    }
}
